### ISSUE TITLE
Show the correct strike order too

### ISSUE THREAD

**Issue by kinow** [CaptainDario/DaKanjiRecognizer#2]
Hey,

This is a great app! I had to learn the number of strokes and order of certain kanji in order to either search it up, or so others could read it. But for new kanji/radicals it's still difficult for me, so this is definitely very handy.

Once I find a kanji with DaKanjiRecognizer, I can search it up in jisho.org, to learn the proper order of strokes. It would be really cool if I could do both in DaKanjiRecognizer.

Perhaps there could be a button to show an extra panel next to the existing one. Once you clicked on the kanji, the extra panel could then be used to show the order as in jisho.org.

Thanks!
Bruno

**Comment by CaptainDario** [comment]
Hi,
that is a good idea! And an implementation would not be that hard too.

If I would search for this kanji 恋. You want a button to [open this site](https://jisho.org/search/%E6%81%8B%20%23kanji)?

**Comment by kinow** [comment]
Either that (like an iframe?), or a custom Qt panel/component, that shows the stroke order. I assume there's some open/free dataset with the kanji + stroke order. But that would be probably more complicated…

**Comment by CaptainDario** [comment]
After some quick google search I found this [data set](https://github.com/KanjiVG/kanjivg). <br/>
I think adding it in the application should not be too hard but will take some time.
As a quick solution I will add a button which links to jisho.org in a second window or automatically opening the web browser.

**Comment by CaptainDario** [comment]
Release 1.1 includes a switch to open the selected prediction on jisho.org.

**Comment by kinow** [comment]
Going to sync the repo and test it @CaptainDario . Thanks for fixing it so quickly!

**Comment by CaptainDario** [comment]
Thank you for the support and tell me if everything works as expected.
But I still need to merge the new fixes into main.
