### ISSUE TITLE
Allow installation on Linux via setup.py or extra requirements.txt file

### ISSUE THREAD

**Issue by kinow** [CaptainDario/DaKanjiRecognizer#3]
Hi,

I just finished installing DaKanjiRecognizer on Ubuntu Linux. I used Anaconda Python 3.8, and a virtual environment. First I tried using the two requirements.txt files, but they both have a Windows only dependency.

Replacing

```
tflite-runtime @ https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp38-cp38-win_amd64.whl
```

by 

```
tflite-runtime @ https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl
```

fixed the issue.

Would it be possible to use a `setup.py` script that inspects the operating system (probably not possible I guess), or maybe have `requirements_rel.txt` without that dependency, and two files, each with

```
# file requirements_rel-linux.txt
-r requirements_rel.txt
tflite-runtime @ https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl
```

Or maybe another approach to allow multiplatform support?

Thanks!
Bruno

**Comment by CaptainDario** [comment]
Hello,
Thank you for your detailed info!
I am sure I can add the correct links for the different systems.
But also the ```setup.py``` is a great idea which i will add very soon.

But in the end best would be to have a standalone executable for MacOS, Windows and Linux.

**Comment by kinow** [comment]
>But in the end best would be to have a standalone executable for MacOS, Windows and Linux.

That'd be definitely very useful! Thanks!

**Comment by CaptainDario** [comment]
I will try to package the application at least on Linux in the coming days.

But for now I have updated the README for tflite-runtime installation.
You can take a look [here](https://github.com/CaptainDario/DaKanjiRecognizer/tree/Fix-dependencies_build#running-from-source)

**Comment by CaptainDario** [comment]
#6

**Comment by CaptainDario** [comment]
For now this is fixed by this pull request #7 .
But I will provide a Linux executable (probably MacOS too) in the near future #6 and #5 .

**Comment by CaptainDario** [comment]
- [ ] #5 - Provide a MacOS executable
- [ ] #6 - Provide a Linux executable

**Comment by CaptainDario** [comment]
Version 1.1 supports Linux (Ubuntu 20.4) and an executable is provided.

**Comment by kinow** [comment]
Thanks @CaptainDario !
